### PR TITLE
EHN change "preprint" to "neuroview"

### PR DESCRIPTION
**Pull request by htwangtw**
This includes:
* markdown content and filename
* figure file name
* book building utilities

The _content_ of `brainhack_book/neuroview_manuscript.md` is still the preprint version.

Another issue we should close is issue #32. Can do it in this PR if we have a clean doc :smile:

### CODE REVIEW

**Review by anibalsolon — APPROVED** [review]
Super duper @htwangtw thank you!! The authorship organization issue would be to go to another PR 🙃

**Review by shawnrhoads — APPROVED** [review]
Thanks for making these updates so quickly! Looks good to me!

Should we also update this now? Or wait until the manuscript is "in print"! :)
> *Note: This is a version for community review on psyarxiv and does not constitute the final version of the manuscript.*
> [Authors & Affiliations TBD]

**Comment by htwangtw** [comment]
> Thanks for making these updates so quickly! Looks good to me!
> 
> Should we also update this now? Or wait until the manuscript is "in print"! :)
> 
> > _Note: This is a version for community review on psyarxiv and does not constitute the final version of the manuscript._
> > [Authors & Affiliations TBD]

I would wait until the manuscript is in print :thinking:

**Review by SNeuroble — APPROVED** [review]
Looks good to me!

**Pull request merged**
