### PR TITLE
ADD contributors' table page

### PR DESCRIPTION
**Pull request by htwangtw**
I would like to have your input on my current progress with the contributor's information page. 

The markdown table is really wide. I am not sure how pretty we want this to be for the preprint.
Another thing is headers with two levels. For example, at the very back of the table, there are cells indicating the contribution to sections of the paper. Markdown doesn't support two levels in the header so I have to place the lower level as part of the body. 
image

I think it's easier to understand to build this branch locally to see what is going on. Sing off for today!

### CODE REVIEW

**Comment by htwangtw** [comment]
Alright I have a big update that is probably beyond the scope of the original PR. Partly implemented some stuff discussed with @shawnrhoads in PR #14 
I have test everything locally and on the main branch of my fork to make sure everything works
1. `mdtable.py` now accept input `acknowledgements` and `contributors`
2. add `osfclient` to environment dependency and download the affiliation table to `data` through osf cli
3. add simple `Makefile` to compile contributions and acknowledgement page, and build jupyter book
4. use `make` in GitHub Action to compile markdown table related pages and build jupyer book

For now I still have a local copy of the contribution table under `data` and all the pages built locally, but in theory we don't need that in the future. We can trigger the build when @Remi-Gau update the OSF data etc. The contribution page will be built together, fetch latest update from osf with the GitHub Action. 
@PeerHerholz if you think this is going to create too many merge conflict, I am happy to revert things back.

One final part is some description that goes before the contributors table. Here's my draft:

> We thank all the individuals who contributed to the creation of the manuscript and the support of Brainhack community towards this project. The current list of autors marks all parties involved to date and details of their contributions. As the Jupyter Book continue to grow with new content, new contributors will be added to this page.

I would really appriciate some one to edit it and make it better!! (@shawnrhoads ?)

**Review by shawnrhoads — APPROVED** [review]
Wow, this is phenomenal!!!! 🤩 🤩 🚀 

If I'm following all of this correctly, then the `affiliation_and_consent_for_the_brainhack_neuroview_preprint_source.tsv` file from OSF is written to `data/contributors.tsv` file and that is written to `contributors.md`? WOW! 😍 

Two quick points:
- Line 14-16 in `Makefile`: typo in `brainhack_book/contributiors.md` and `echo "build contributiors.md"`
- For now, should we remove "Some descriptions here." from `data/contributors_descriptions.md`? In the future, could be nice to include a link to the authorship agreement page.

**Comment by shawnrhoads** [comment]
> Alright I have a big update that is probably beyond the scope of the original PR. Partly implemented some stuff discussed with @shawnrhoads in PR #14
> I have test everything locally and on the main branch of my fork to make sure everything works
> 
>     1. `mdtable.py` now accept input `acknowledgements` and `contributors`
> 
>     2. add `osfclient` to environment dependency and download the affiliation table to `data` through osf cli
> 
>     3. add simple `Makefile` to compile contributions and acknowledgement page, and build jupyter book
> 
>     4. use `make` in GitHub Action to compile markdown table related pages and build jupyer book
> 
> 
> For now I still have a local copy of the contribution table under `data` and all the pages built locally, but in theory we don't need that in the future. We can trigger the build when @Remi-Gau update the OSF data etc. The contribution page will be built together, fetch latest update from osf with the GitHub Action.
> @PeerHerholz if you think this is going to create too many merge conflict, I am happy to revert things back.
> 
> One final part is some description that goes before the contributors table. Here's my draft:
> 
> > We thank all the individuals who contributed to the creation of the manuscript and the support of Brainhack community towards this project. The current list of autors marks all parties involved to date and details of their contributions. As the Jupyter Book continue to grow with new content, new contributors will be added to this page.
> 
> I would really appriciate some one to edit it and make it better!! (@shawnrhoads ?)

Ooops! I missed this comment somehow (until checking my email)! The description looks good to me (minor typo in "The current list of autors").

I'll have some time to review one more time later tonight :)

**Comment by shawnrhoads** [comment]
> Ooops! I missed this comment somehow (until checking my email)! The description looks good to me (minor typo in "The current list of autors").
> 
> I'll have some time to review one more time later tonight :)

Okay! Yes, looks good to me! Here's a description with my minor edits:

> We thank all the individuals who contributed to the creation of the manuscript and the support of Brainhack community towards this project. The current list of authors marks all involved to date and details their contributions. As the Jupyter Book continues to grow with new content and the Brainhack community continues to evolve, new contributors will be added to this page.

I'll also bring down my points from earlier and add one more:
- In the future, could be nice to include a link to the authorship agreement page at the end of the description.
- Lines 14-16 in `Makefile`: typo in `brainhack_book/contributiors.md` and `echo "build contributiors.md"`
- I wonder if we should keep emails anonymous for privacy purposes and to avoid potential spam mail? Shouldn't be too difficult, right?

**Review by Remi-Gau — APPROVED** [review]
Wow this looks insanely cool @htwangtw !!!

One question: maybe my quick read of the code is at fault but it seems we are keeping the emails in the table in the end?

I think that ORCID, OSF ID and twitter handle are fine to keep but I am always worried of stuff getting crawled for emails by spambots.

What do you think?

**Comment by Remi-Gau** [comment]
Just saw @shawnrhoads comment about emails. Almost noon and still asleep. Way to go Rémi.

**Comment by htwangtw** [comment]
We can remove the emails indeed and perhaps add something like this to point to the osf data:
> To see the full contributor information, please refer to the [OSF project](https://link/to/osf/)

I haven't removed email yet but I am on it @Remi-Gau

**Comment by Remi-Gau** [comment]
> We can remove the emails indeed and perhaps add something like this to point to the osf data:
> 
> > To see the full contributor information, please refer to the [OSF project](https://link/to/osf/)
> 

Yes!!! Will defo do for now.

Later on we could even hyperlink to each contributor's OSF profile? Not urgent but something like this could be cool.

**Comment by htwangtw** [comment]
Close for now. Quote from @Remi-Gau :

> But as long as we got all our ducks in a row for the final product I am OK with any option for now.
> 
> :duck: :duck: :duck: :duck: :duck:

**Comment by htwangtw** [comment]
Not this one - PANIK

**Comment by htwangtw** [comment]
Email removed. Ready to go!

**Review by katjaq — APPROVED** [review]
Oh this is just amazing! 🚀  ✨  Thank you so much for all the work you all put in there! This workflow is awesome! 
Everything looks fantastic and working to me, all links as well. So fireworks to merge this PR from my side as well! 🎉 🎊 
Maybe – this PR will then be closed I guess – so maybe open a new enhancement issue to keep @Remi-Gau 's thought to "Later on we could even hyperlink to each contributor's OSF profile? Not urgent but something like this could be cool." 

absolutely fantastic work! Merge! \\\ö// 💚

**Pull request merged**
