### PR TITLE
Add landing page text and first interactive figure

### PR DESCRIPTION
**Pull request by katjaq**
Hey @PeerHerholz and @shawnrhoads and @htwangtw and everyone who can review this quickly :D

We added the landing page text to the jupy book together with @yasminebassil and @anibalsolon and @SNeuroble 

And then @anibalsolon and I added our first interactive figure :D (in the separate tab you had planned to fill with figure, replacing the test visual). Wuhuu! more to come... :D We also removed the logo from the landing page as it was redundant with the one on the side 🙃

We added a `question.md` issue template so that we were able to fill in some content to the heading you had in the landing page file for people to ask questions/give feedback (with a note to PsyArXiv for preprint related questions and a link to `questions.md` issue template for book related questions :)

Hope that looks good to you!! \\\ö// 

I learnt co-author commits!!! GitHub is so fantastic!! 🥰😍😃🙃💛

### CODE REVIEW

**Review by htwangtw — APPROVED** [review]
Looks great :D

**Review by PeerHerholz — APPROVED** [review]
Great stuff folks. As far as I can tell, everything looks good to go and should work as expected.

**Review by shawnrhoads — APPROVED** [review]
Awesome!!! Amazing work! 🤩🤩🤩

Only question is: do we want to add a link to the growing list of acknowledgments to the landing page as well?

**Comment by htwangtw** [comment]
I think the text is very self-explanatory for the current status and indicated it will be updated. 
I would prefer to not change things that are working before preprint. What do people think?

**Comment by shawnrhoads** [comment]
> I think the text is very self-explanatory for the current status and indicated it will be updated.
> I would prefer to not change things that are working before preprint. What do people think?

Sounds good to me!

**Pull request merged**
