### PR TITLE
ADD markdown table generator and acknowledgement page

### PR DESCRIPTION
**Pull request by htwangtw**
I have completed a very basic csv/tsv to markdown table parser. 
`mdtable.py` generated a basic acknowledgements page with `mdtable.py`.
The acknowledgements page has a table and title but nothing else.
I updated `_toc.yml` for the sake of testing.

Should I update the contribution table in the same PR?

### CODE REVIEW

**Review by katjaq — APPROVED** [review]
This is just awesome!! Fantastic work @htwangtw and so fast 🚀 😃 

One question with regards to the content of the `acknowledgements.md` file: @shawnrhoads has curated the first part (text paragraph) of the acknowledgements ending on a phrase that introduces the acknowledgements table – so this text should ideally be included in a final acknowledgments markdownfile (right before your table). Do you see a best way how to integrate this?

The python script is great, clean, and commented. If you want, you could add a little head saying what the script does, author, year, and usage how to run it. 

Thanks for spotting the Umlaute :)

Great to see this all come together! 🚀  Green light for the merge from my end.

**Comment by htwangtw** [comment]
@katjaq thanks!!! 
It was a quick thing to do than I expected to be honest :see_no_evil: 
Thanks for the heads up about the text curated by @shawnrhoads! 
I am thinking of adding the text in a separated file named `acknowledgements_header.md`, or something along this line. The script can read the file and simply append the table to the text. This way we can edit the text paragraph independently.

I will add more description in the script as suggested.

**Review by katjaq — APPROVED** [review]
wow! awesome script documentation! 🚀

**Review by shawnrhoads — APPROVED** [review]
Amazing!! Thanks @htwangtw! 🤩🤩🤩

I just added small changes that @katjaq recommended we include in the descriptions. Other than that, it looks great to me!

**Comment by shawnrhoads** [comment]
I also just thought of this idea for the future. Not at all urgent, but should be fairly easy to implement later (@PeerHerholz can weigh in):
- If the idea is to run `mdtable.py` to generate the contributors and acknowledgements pages, then it might be nice to add this to a workflow. For example, we can just add it into the `deploy-book` action (which can be addressed with issue #15). Or, is it possible to add a different github action to trigger whenever `data/acknowledgements.csv` or `data/contributors.csv` is changed?)
- For organizational purposes, should we move `brainhack_book/mdtable.py` to a new directory: `scripts/mdtable.py`?
- We could also make `mdtable.py` more general-purpose if we use a workflow (i.e., specifying usage for either acknowledgements or contributors). 

Here's some pseudo-code for workflow:
```
if acknowledgements.csv is changed:
    # generate new brainhack_book/acknowledgements.md
    python scripts/mdtable.py acknowledgements

if contributors.csv is changed:
    # generate new brainhack_book/contributors.md
    python scripts/mdtable.py contributors
```

**Comment by shawnrhoads** [comment]
> 
> 
> wow! awesome script documentation! 🚀
> 
> Looks great the combination of text and table! Did someone have feedback on the table header? (Brainhack Events or Events?)
> Ready to go for the merge! PR approved! :D

Oh also, yes! I think changing the table header to just "Events" is a good idea! 👍

**Comment by katjaq** [comment]
hello dear @shawnrhoads and @htwangtw ! I am sooo sorry!! 🙈🙃 I completely forgot to add all Paris event sponsors!  
@deep-introspection spotted it (thanks Guillaume!! 🚀 ) and so I would like to kindly ask you if you could add them into the acknowledgments table here:  
Institut Pasteur with the events, La Paillasse, and Mozilla Lab Paris. 

Thank you! I am sorry to put that extra work on you! 🙈

**Comment by htwangtw** [comment]
> Oh also, yes! I think changing the table header to just "Event" is a good idea! +1

Changed the header to Event now! @shawnrhoads 
Love your suggestion for the long term maintainece.
For triggering the script, I was thinking to have a `Makefile` since it's easy to specify dependencies in it.
It can also include the book build etc. and have the Github Action to run make commands. 
The content would be like this for the acknowledgements:
```Makefile
brainhack_book/acknowledgements.md: data/acknowledgements.csv
   python scripts/mdtable.py
```
(I am not very familiar with Makefile or GitHub Action so any suggestion is welcome!!!)
Any how I think this should be a different PR. Happy to be involved!

Right now the MarkdownTable class can handle the contributor csv passed to me from @Remi-Gau and output all contents as they are. 
I am trying to write a parser for contributor table and collaspe some information to make it look nicer in markdown.

@katjaq - no problems at all!! I have added the three to the sponsors column. Can you add details to the event column?

**Review by katjaq — APPROVED** [review]
Thanks so much @htwangtw 
I am sorry, I first added the events to the md 🙈, but then added them to the csv file as well, so should be fine. 
Thanks for adding the sponsors ! 
now, seems this is ready to be merged? (I cannot see the events I added right now in the changed files....😳 Hope they are there 😂

**Review by Remi-Gau — APPROVED** [review]
Had only a quick look.
The python code would take me too long to cross check  thourouhgly now.

I suggest opening an issue to remember to set up a workflow to automate the creaation of the MD on build

**Comment by PeerHerholz** [comment]
Looks like we have everything we need for the merge, I'll go ahead and initiate the engine.

**Pull request merged**
