### PR TITLE
[INFRA] update pipeline to create author lists

### PR DESCRIPTION
**Pull request by Remi-Gau**
What this PR does

Adds instructions on how to update the author lists of the preprint on the OSF project, on psyarxiv  and on how to generate the new list of authors and affiliations to be added to the google doc of the manuscript.

- [x] transfer raw.tsv data from OSF to this repo (to allow updating it by PR)
- [x] update make file to copy from this local file
- [x] add instructions on how to update author list
- [x] update author list
- [x] regenerate new pages of contributors

### CODE REVIEW

**Comment by Remi-Gau** [comment]
I am getting an error when running the `make manuscript` command:

```
(brainhack) remi@remi-XPS-15-9570:~/github/brainhack_jupyter_book$ make manuscript

python scripts/neuroview_author_ranking.py
handle this case by first name: Gau
Traceback (most recent call last):
  File "scripts/neuroview_author_ranking.py", line 91, in <module>
    "First": lines["First"].iloc[0],
  File "/home/remi/github/brainhack_jupyter_book/brainhack/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/remi/github/brainhack_jupyter_book/brainhack/lib/python3.8/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/remi/github/brainhack_jupyter_book/brainhack/lib/python3.8/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
Makefile:41: recipe for target 'manuscript' failed
make: *** [manuscript] Error 1
```

Can finish having a look later but in case anyone has got the time.

**Comment by htwangtw** [comment]
I am on it - I remeber this was because partial match in @Remi-Gau's last name will also give me @SamGuay, so I had to rule out the special case with an extra if statement

**Review by htwangtw — APPROVED** [review]
Thanks for fixing my typos! LGTM

**Comment by Remi-Gau** [comment]
I also added the output from running make to the PR and updated the "instructions".

Hope it is clear enough.

**Review by anibalsolon — APPROVED** [review]
Looks great, thank you!

**Review by SamGuay — APPROVED** [review]

**Pull request merged**
