### PR TITLE
Update glossary.md

### PR DESCRIPTION
**Pull request by r03ert0**
Added definition of "unconference" from wikipedia, together with a link to the full article.

### CODE REVIEW

**Review by anibalsolon — CHANGES_REQUESTED** [review]
Thank you, @r03ert0! The definition looks good to me.

What got me wondering is how to manage references, such as your Wikipedia one. I may be unaware of it, but it is not defined yet how to deal with it. There are two groups of references: the *See Also*, to point to deeper content, and *References / Citations*, to point to the bases of a definition.

@PeerHerholz @htwangtw @complexbrains would the [bibliography support from Jupyter Book](https://jupyterbook.org/content/citations.html#citations-and-bibliographies) be a good alternative?

**Comment by htwangtw** [comment]
Thanks @r03ert0 ! I am happy with more new content added to the glossary!

@anibalsolon Re: referencing we don't have a system in place to handle them yet. 

> References / Citations, to point to the bases of a definition
... would the bibliography support from Jupyter Book be a good alternative?

This is a good idea! Seems not too difficult to do! It would be great if we can address this within this PR.

> the See Also, to point to deeper content

This can be implemented through [section labels](https://jupyterbook.org/content/citations.html#reference-section-labels) and we have already implemented that for the manuscript referencing. The glossary page of the jupyterbook documentation actually is a very good example that we can follow and implement. We can have this implemented in a different PR, or this one. Even if we address this in a different PR, this is a good time to do it since we have only a few entries, it's quicker to make edits now and for newcomers they will have some examples to follow!

**Review by htwangtw — CHANGES_REQUESTED** [review]
Thanks @r03ert0 ! I am happy with more new content added to the glossary!

@anibalsolon Re: referencing we don't have a system in place to handle them yet. 

> References / Citations, to point to the bases of a definition
... would the bibliography support from Jupyter Book be a good alternative?

This is a good idea! Seems not too difficult to do! It would be great if we can address this within this PR.

> the See Also, to point to deeper content

This can be implemented through [section labels](https://jupyterbook.org/content/citations.html#reference-section-labels) and we have already implemented that for the manuscript referencing. The glossary page of the jupyterbook documentation actually is a very good example that we can follow and implement. We can have this implemented in a different PR, or this one. Even if we address this in a different PR, this is a good time to do it since we have only a few entries, it's quicker to make edits now and for newcomers they will have some examples to follow!

**Comment by anibalsolon** [comment]
@htwangtw @r03ert0 WYT?

image

image

**Review by htwangtw — APPROVED** [review]
LGTM

**Review by anibalsolon — APPROVED** [review]

**Review by vogelbac — APPROVED** [review]
looks good

**Pull request merged**
