### PR TITLE
add clean data csv with all brainhack events from the first in 2012…

### PR DESCRIPTION
**Pull request by katjaq**
…up to the end of 2020.

I had started to curate events in a Google spreadsheet and then circulated the link among the community to help fill in all events and not miss any :) We could think about providing a link to this spreadhseet in the Jupyter book, to allow the community to continuously update it and keep it a living resource for our next data viz. We can then occasionally save exports of that spreadsheet to this repo – for example for future versions of this jupyter book, etc. What do you think?

I attach some visual explorations of the evolution of brainhack over time which are based on the `brainhack-timeline.csv` file included in this PR. These will not go to the paper (the paper holds a map with bubbles for all Brainhack events per city :)

Where could I put possible figure explorations? Do I make a directory such as `brainhack_jupyter_book/figures`?  And inside I create a `Readme.md` to put the figures for display for discussion? :) (If you agree, I would do this in a separate PR).

Here are some visual explorations of the evoloution of Brainhack, and to show what is inside the csv file in this PR:

Events per year per country
evolution-of-brainhack_country_year

and here, showing the impact of Brainhack Global :)
evolution-of-brainhack_country_dates

and here just showing the sheer amount of events explosion over the years <3

date-country-city_color-by-country_emptyspace_empty

### CODE REVIEW

**Comment by PeerHerholz** [comment]
Ahoi hoi @katjaq (and everyone),
 
thx so much @katjaq for your efforts in collecting this information and creating the figures (they look fantastic!!).
IMHO this is a great example of content that would fit amazingly well in the `jupyter book`.


> I had started to curate events in a Google spreadsheet and then circulated the link among the community to help fill in all events and not miss any :) We could think about providing a link to this spreadhseet in the Jupyter book, to allow the community to continuously update it and keep it a living resource for our next data viz. We can then occasionally save exports of that spreadsheet to this repo – for example for future versions of this jupyter book, etc. What do you think? 

+1 re linking the google spreadsheet in the `jupyter book`.  Yeah, ideally we would export the spreadsheet to `csv` on a regular basis, linking them to specific versions of the `jupyter book`. 

> Where could I put possible figure explorations? Do I make a directory such as brainhack_jupyter_book/figures? And inside I create a Readme.md to put the figures for display for discussion? :) (If you agree, I would do this in a separate PR).

I think this depends on how we want to set things up. Ideally, we would include the code that generates the figures and run it during the `build` so that we have everything in place and allow easy updates. For example, the figure added by @jhlegarreta works in this way: we include the code in the corresponding `notebook` and run it during the `build` within which we use the `csv` present in the repo.

> Here are some visual explorations of the evoloution of Brainhack, and to show what is inside the csv file in this PR:

As said before, amazing graphics. @katjaq would it be possible to have interactive versions (e.g. using `plotly`)?

@anibalsolon, @sofievdbos, @complexbrains and @SamGuay, I set you folks as reviewers. Please let me know, if don't want to do a review/don't have time/want to suggest someone else. Sorry for brashly tagging you here.

Cheers, Peer

**Comment by jhlegarreta** [comment]
> I think this depends on how we want to set things up. Ideally, we would include the code that generates the figures and run it during the build so that we have everything in place and allow easy updates. For example, the figure added by @jhlegarreta works in this way: we include the code in the corresponding notebook and run it during the build within which we use the csv present in the repo.

The new data and plots are :ok_hand: . In the interest of consistency, I'd say that having a single `csv` data file is desirable: the existing [data file](https://github.com/brainhackorg/brainhack_jupyter_book/blob/main/data/bhg_sites_test.csv) could ideally:
- Be renamed to e.g. `bhg_sites.csv` or whatever is deemed appropriate.
- The columns in the actual file in this PR be added to the former as appropriate. A few thoughts on this:
  - The country names for the exiting visualisation tool are expected in a given format (e.g. `United States of America`  vs. `USA`). Maybe there are tools out there to automatically retrieve the ISO-3 country codes if the long names do not fit well in some plots.
  - Maybe the geographical coordinates of the countries can be retrieved in the same format of the [current geography data files](https://github.com/brainhackorg/brainhack_jupyter_book/tree/main/data) (or maybe another visualisation tool can pull that data without needing to store it) so that we avoid hard-coding it (as long as the data corresponds to the cities and not the institutions).
  - The existing visualisation tool uses `bokeh` instead of `plotly`.
  - Hence, all data would be contained in a single file, as long as that makes sense or to the extent that is possible. That would allow us to avoid duplicating data, reducing maintenance, and incurring in inconsistencies.

**Comment by anibalsolon** [comment]
The plots are beautiful @katjaq ! The first is my favorite 😊 I just wonder how impact is quantified in the second, I'm sorry I didn't follow.

Agreeing with @jhlegarreta , I'd like to also suggest to maintain the ISO date format YYYY-MM-DD and dropping the year column since it is redundant. It may be cumbersome to gather but useful to store which days the brainhacks actually happened, instead of just the first day, to check for overlaps and durations.

> +1 re linking the google spreadsheet in the jupyter book. Yeah, ideally we would export the spreadsheet to csv on a regular basis, linking them to specific versions of the jupyter book.
 
It is easy as setting up a cron github action downloading from this example URL:
https://docs.google.com/spreadsheets/d/1ZgOVCKOI8k7GlacMvDO14PPOoxEZIPApVJwuM0MMU-8/export?format=csv


Another suggestion would be to encode the `online` information from the city name into a new column e.g. `format`. There will be more online brainhacks, and IMO even after the pandemic: this format works really well.

**Comment by anibalsolon** [comment]
Hey, so discussing with @katjaq , the process to include new sites/events would be better to make through PRs, given that spreadsheets would need to be cared for (i.e. it is easy to change the data, and to make mistakes) and Google services are famous for not being accessible in some countries (I say it in the plural, but only know China tbh).

Making the process through PR, although requiring some technical aspects, is controllable and accessible. Versioning would be easier too. WYT @PeerHerholz @jhlegarreta ?

**Comment by katjaq** [comment]
Hey all! Thank you so much for the kind and enthusiastic comments! 😍  Yeees, this community is amazing. 🚀 

@PeerHerholz Thanks for the feedback and suggestions. @anibalsolon didn't spoil anything, but we are indeed working on several interactive versions 🥰 (future PR, here first focus on data 🙃)

@jhlegarreta Thank you for the comments on how to follow clean data conventions. 😍 I am learning 🙈 
* I deleted the redundant year column, and 
* @anibalsolon and I renamed countries correctly to iso standard (UK was shortest and is the longest now 🙈) and 
* he also swapped latitude and longitude into correct order 🙃
* we added a continent column
* for the moment I did not include "institution column" as I think city is a great level of detail already and it would be sooooo much work to get the info, if ever possible for many of the sites. Hope it's okay. 
* Same for websites: It would be a terrible amount of work, including the webarchive, as many of the links are dead by now, and many of the current ones may as well die in the near future... and also I cannot see here in this specific sheet the need for the website as the events are and will be in the past. I hope it is okay that we left it out.

@anibalsolon Thank you so much for helping me sort things out :D You suggested to add 
* duration of the events: same as above : a lot of work to find these info, if ever possible :( and then most of them were 3 days, and only very very few exceptions were 1- or 2-day events. You also suggested to add a 
* `format` column to accommodate better the online (which I just wildly put in `City online`, keeping the country and city information. But it is lovely to aim at keeping the online part forever beyond pandemic and making hybrid events in future :) <3 For now, I have not added the column. But just because I forgot 🙈 🙃. We can maybe keep that thought for future :) 

Thank you all again! \\\ö// I hope this is ready to be merged! 😃

**Comment by katjaq** [comment]
Hey all! Thank you so much for the kind and enthusiastic comments! 😍  Yeees, this community is amazing. 🚀 

@PeerHerholz Thanks for the feedback and suggestions. @anibalsolon didn't spoil anything, but we are indeed working on several interactive versions 🥰 (future PR, here first focus on data 🙃)

@jhlegarreta Thank you for the comments on how to follow clean data conventions. 😍 I am learning 🙈 
* I deleted the redundant year column, and 
* @anibalsolon and I renamed countries correctly to iso standard (UK was shortest and is the longest now 🙈) and 
* he also swapped latitude and longitude into correct order 🙃
* we added a continent column
* for the moment I did not include "institution column" as I think city is a great level of detail already and it would be sooooo much work to get the info, if ever possible for many of the sites. Hope it's okay. 
* Same for websites: It would be a terrible amount of work, including the webarchive, as many of the links are dead by now, and many of the current ones may as well die in the near future... and also I cannot see here in this specific sheet the need for the website as the events are and will be in the past. I hope it is okay that we left it out.

@anibalsolon Thank you so much for helping me sort things out :D You suggested to add 
* duration of the events: same as above : a lot of work to find these info, if ever possible :( and then most of them were 3 days, and only very very few exceptions were 1- or 2-day events. You also suggested to add a 
* `format` column to accommodate better the online (which I just wildly put in `City online`, keeping the country and city information. But it is lovely to aim at keeping the online part forever beyond pandemic and making hybrid events in future :) <3 For now, I have not added the column. But just because I forgot 🙈 🙃. We can maybe keep that thought for future :) 

Thank you all again! \\\ö// I hope this is ready to be merged! 😃

**Comment by jhlegarreta** [comment]
> Hey, so discussing with @katjaq , the process to include new sites/events would be better to make through PRs in the CSV file, given that spreadsheets would need to be cared for (i.e. it is easy to change the data, and to make mistakes) and Google services are famous for not being accessible in some countries (I say it in the plural, but only know China tbh). (EDIT: @katjaq updated me about the list of countries that blocks Google grimacing so, even more to the point).

> Making the process through PR, although requiring some technical aspects, is controllable and accessible. Versioning would be easier too. WYT @PeerHerholz @jhlegarreta ?

Not sure where google comes into play here. I placed the data I had used to generate the plot into the [`data`](https://github.com/brainhackorg/brainhack_jupyter_book/tree/main/data) folder. And I did grant that it was cherry-picked data to see if the notebook worked/was feasible, and to have a starting point upon which we could improve things.

Now one can also argue that `OSF` might be a better place than `GitHub` to store some of the data (ideally separating the code from the data, but the `OSF` space now got everything related to the paper). But the essential thing to me is to be able to version the data, to be able to update it as new editions happen, and to avoid having multiple copies, some of which with incomplete, redundant or inconsistent data.

I do believe that the Brainhack drive is not the place to have such data, although until now we have stored it there.

That being said,
- Cleaning the data is time-consuming, and at times gets little acknowledgement I find.
- We do not have a clean/automated (i.e. a script) way to add the data from newer editions to existing data sheets. At some point I think that would save us work, but developing and maintaining (i.e. fields might change, be added, etc. across years) the script requires work as well. We do not have a CMS to manage that, which complicates things, but have to live with it.

As for @katjaq 's comments:
> - for the moment I did not include "institution column" as I think city is a great level of detail already and it would be sooooo much work to get the info, if ever possible for many of the sites. Hope it's okay.
> - Same for websites: It would be a terrible amount of work, including the webarchive, as many of the links are dead by now, and many of the current ones may as well die in the near future... and also I cannot see here in this specific sheet the need for the website as the events are and will be in the past. I hope it is okay that we left it out.

Both data exist in one of the multiple copies of the paper shared drives (`brainhack-neuroview/Data/bhg_sites`), but can be added at a later time, granting all the unknowns you mention.

I had a look at the `brainhack-timeline.csv` file in this PR, and I think it has the necessary data for the [plot notebook](https://github.com/brainhackorg/brainhack_jupyter_book/blob/main/brainhack_book/geographical_distribution.ipynb) to work, as it contains the fields of the [test data](https://github.com/brainhackorg/brainhack_jupyter_book/blob/main/data/bhg_sites_test.csv) I used to develop the script/generate the plot.

I see that the data format changes a little bit, so the notebook would require to be adjusted, and see if it works. Does not seem a complicated change. It might take me some time/weeks before I can devote time to it, so on my end likely not to be before the preprint is out.

So, thanks for doing this and sorry for the lengthy message.

**Comment by anibalsolon** [comment]
@jhlegarreta

> Not sure where google comes into play here.

The spreadsheet is where the data was initially collected, so to reduce the barrier for the community to add new data. I believe we are good to keep it in Github, to be versioned along with the code, and point the community to open PRs (or we add it when it gets added to e.g. the Brainhack homepage).

> It might take me some time/weeks before I can devote time to it, so on my end likely not to be before the preprint is out.

I can provide with the fixes it might need 👌🏻

**Comment by jhlegarreta** [comment]
> I can provide with the fixes it might need 👌🏻

Go ahead if you feel like you'd like to give it a try. Thanks.

Changing these two blocks in the Jupyter notebook:
```
path = "../data"
fnames = [os.path.join(path, elem)
          for elem in sorted(os.listdir(path))
          if os.path.isfile(os.path.join(path, elem)) and
          elem.endswith(".csv")]
```
to get the appropriate file (i.e. the one in this PR), and
```
df_year = event_df[event_df["dates (DD/MM/YYYY)"].str.contains(
    year, na=False, regex=False)]
```
to parse the year correctly according to the format in the data file in this PR should be enough. If that produces a map correctly, +1 for merging this.

**Comment by jhlegarreta** [comment]
@anibalsolon :100: Thanks.

**Comment by anibalsolon** [comment]
Alrighty, @jhlegarreta @PeerHerholz @SamGuay @complexbrains @sofievdbos , CSV and Jupyter notebook updated and tested! I've also removed the test file, so to avoid any confusion. It would be great if you could review this PR — I touched the code, so my review would be biased now 🙃 Please let us know if there is any question or idea you have in mind!

**Review by SamGuay — APPROVED** [review]

**Review by jhlegarreta — APPROVED** [review]
Looks :ok_hand: to me. Further enhancements can come in separate PRs so that we move forward.

**Comment by katjaq** [comment]
Hello dear @PeerHerholz – I would like to kindly ask you * ping * if it would be possible to merge our PR so that the data is available via the repo and will be time stamp included once Remi gets ready to stamp the preprint version?
I got great support from @jhlegarreta and @anibalsolon with respect to best standards and formatting ✨  and so the file should be good to be included as is now :) 🚀 

We are preparing the landing page and interactive figure with @anibalsolon  – will come in a separate next PR 😊

Thank you! :)

**Comment by PeerHerholz** [comment]
Ahoi hoi there,

this `PR` had 5 reviewers for some reasons hehe....I removed @sofievdbos and @complexbrains from the list so that @anibalsolon can do the last required review given he also worked on this `PR`. Once that is in, whoever is first can click `merge`. However, I will also keep this tab open to `merge` it asap. 

Thanks folks!

**Review by anibalsolon — APPROVED** [review]

**Comment by anibalsolon** [comment]
@PeerHerholz it is only counting the reviews from who has the write access to the original repo 😄 LMAO! It is clear that it has been approved already... Let me merge it.

**Pull request merged**
