### PR TITLE
Created some new neuroview landing pages and updated links; reorganized TOC

### PR DESCRIPTION
**Pull request by SNeuroble**
Co-authored-by: htwangtw <htwangtw@gmail.com>

### CODE REVIEW

**Comment by htwangtw** [comment]
Just for clarification, I will update my other PR once this is merged! This edit will resolve some questions I have over what page to keep etc.
@SNeuroble if you can migrate the non-markdown table edits in the contributors and acknowledgement to their counter part under `data/` that would be helpful!

**Comment by SNeuroble** [comment]
Alright, @htwangtw and I discussed and we will update data/ after this PR is merged!

**Review by shawnrhoads — APPROVED** [review]
Awesome! If we should merge this PR before PR #25, then let's move forward!

All looks good to me! Just one thing I noticed. The intro paragraph for the acknowledgments page has been changed a few times. At first, we decided on the following text in issue #9 (to not single out any individual organizations), which was implemented with PR #14:

> We acknowledge all the individuals who contributed and will make ongoing contributions to the insights and resources included in this Jupyter book. Moreover, we would like to acknowledge all Brainhack organizers, supporters, presenters, and participants for their contribution to growing and maintaining this community. The benefits described in this manuscript would not be possible without them. We also thank all institutions, labs, and organisations who have helped this community grow, meet in stimulating environments, and add an excellent educational resource pool and agenda. With an expanding community, Brainhack’s support network keeps growing and we thank all labs and individual researchers for their dedication and expertise offered to this community.

This was updated with PR #24 (adding the following text to the new `neuroview_acknowledgments.md` page), but [then changed back](https://github.com/brainhackorg/brainhack_jupyter_book/pull/25/commits/5a01a413aa774d7ab6632a1bfff77687af03741c) in PR #25. @katjaq commented "aiming at not offending any sponsor, we do not specifically mention any of them by name above. :)"

> A special thank you to the teams associated with ReproNim, INCF, and Nilearn, for their involvement in this community with ideas, tools, energy and funding, and for playing a central role in shaping Brainhack into what it is today. We also thank all institutions, labs, and organisations who have helped this community grow, meet in stimulating environments, and add an excellent educational resource pool and agenda, particularly OHBM, OpenNeuro, NeuroMod, CONP, OHBM Australia, Wellcome Trust, LUDMER, NIH, and UNIQUE. 

Is it intentional to include "special" thank yous to these specific organizations for the NeuroView manuscript (i.e., thank yous to orgs in the [neuroview acknowledgments](https://github.com/SNeuroble/brainhack_jupyter_book/blob/main/brainhack_book/neuroview_acknowledgments.md) but not the [evolving book acknowledgments](https://github.com/SNeuroble/brainhack_jupyter_book/blob/main/brainhack_book/acknowledgments.md)?)? Thought to bring up just in case! :)

As a side note, I love the additions of "See the latest version of the acknowledgments/contributors page here."

Otherwise, all looks good to me!

**Review by katjaq — APPROVED** [review]
hey @shawnrhoads . Thanks for cross checking all of this so thoroughly and pinging us all.

The special thanks should not appear anywhere at all. They are not part of the manuscript, nor should they be part of the book. I thought I had erased that part everywhere and adapted the acknowledgements to match exactly the manuscript. hm, curious that they keep coming back :D

so, I deleted the special mentions once again ! :D  @htwangtw – is there a source file that is not included here which is different from the ones I had seen and corrected before? 👀 If so , please point me to it and I can adapt it or feel free to adapt it yourself :)

Thank you all so much again!

**Comment by katjaq** [comment]
hey @shawnrhoads . Thanks for cross checking all of this so thoroughly and pinging us all. 

The special thanks should not appear anywhere at all. They are not part of the manuscript, nor should they be part of the book. I thought I had erased that part everywhere and adapted the acknowledgements to match exactly the manuscript. hm, curious that they keep coming back :D

**Comment by htwangtw** [comment]
@katjaq yes you are right! This PR does not include the `data/neuroview_*_descriptions.md`
All the changes you did in #25 should still be there and we can have a final clean up with all things related to `data` in that PR.

**Review by PeerHerholz — APPROVED** [review]
LGTM, merci!

**Comment by PeerHerholz** [comment]
@SNeuroble or @htwangtw, do you want to initiate the `merge sequence` hehe?

**Comment by SNeuroble** [comment]
As usual, thank you all for your quick work + thoughtful discussion on this!

**Pull request merged**
