### PR TITLE
Added and formatted neuroview pages and contents

### PR DESCRIPTION
**Pull request by SNeuroble**
Most files are brainhack_book/neuroview_*
Right now only figure is in brainhack_book/neuroview_contents/
Also organized _toc.md into parts w chapters—right now separating neuroview components into their own part.
From @likeajumprope, @katjaq, and me

### CODE REVIEW

**Review by shawnrhoads — COMMENTED** [review]
Super awesome! The content and new TOC organization look great to me! My only recommendation regarding new content is moving `Figure1.png` into `brainhack_book/static/images/Figure1.png`.

Looks like there will be some inconsistencies with the current build of the book (updated with PR #20). I'm imagining two potential approaches (that would avoid any Git/GitHub gymnastics):

Approach 1
1. resolve conflict for `brainhack_book/_toc.yml` and merge main into `update-neuroview_contents`
2. merge everything
3. update @htwangtw's scripts with the `neuroview*` heuristic and delete any unused files (i.e., those without `neuroview*`) with a new PR (ultimately resolving #18)

Approach 2
1. resolve conflict for `brainhack_book/_toc.yml` and merge main into `update-neuroview_contents`
2. delete `brainhack_book/neuroview_contributors.md` and `brainhack_book/neuroview_acknowledgments.md` containing the older content
3. only merge `Figure1.png`, `brainhack_book/neuroview_figure.md`, and `brainhack_book/neuroview_manuscript.md`
4. ~~let this build fail~~ <-- (update: I'm now realizing that we can also just change the file names with the `neuroview*` heuristic now that main is merged into `update-neuroview_contents`; I might be leaning toward this approach now)
5. update the scripts with the `neuroview*` heuristic with a new PR (ultimately resolving #18)

I'm leaning toward approach 1, but super curious what others think regarding best practices in this situation (is it a little nerdy that I'm kind of excited about figuring this out? ~~probably~~absolutely). 

I think we will have to resolve the conflict and merge main into `update-neuroview_contents` either way, so I can go ahead and do that now 😄

**Comment by SNeuroble** [comment]
Approach 1 sounds good! Should be fairly straightforward to merge everything then reorganize however you'd like.

**Review by katjaq — COMMENTED** [review]
Hello team! This is the first shot, not yet ready for official review 🙃

We have a `neuroview_contributors.md` and a `neuroview_acknowledgements.md` file – @htwangtw could you do your magic again here, and integrate these into a (_neuroview specific?) python build workflow just as you did for the evolving jupyter book part? 💛 

We will also update the figure to the current final version \\\ö//,  and will have to do some more tweaks to the main text (last minute edits based on the latest comments). 

Thanks so much for your help if possible 💚 🚀

**Comment by katjaq** [comment]
haha, overlapping comments – sorry @shawnrhoads ! Thanks for all your comments and suggestions💚.  

I am maybe a bit lost on what the plan is – but I seem to have understood that all neuroview content will be "frozen" as neuroview – and not evolve. This means that it would be better to keep the `acknowledgments` and the `neuroview_acknowledgments` both – and the same for the `contributors` and `neuroview_contributors`. I asked (a little bit ago) whether the neuroview shall remain exactly as the manuscript – and the answer I was given was yes. So maybe don't delete and fuse those 4 files into 2. 🙃 The acknowledgments in the jupy book will evolve as new Brainhacks will happen, and so will the contributors section in the jupy book...

We will place the final figure into static as you suggest – thank you 🚀 

tomorrow.... 🙃 now, signing off....

**Comment by shawnrhoads** [comment]
Ah, I see! Yes, all of what @katjaq said sounds perfect to me! 😄

**Review by htwangtw — COMMENTED** [review]
Thanks @SNeuroble and @likeajumprope getting this started!

Thanks @shawnrhoads for the guidance to resolve merge conflicts! It makes things assigned to me by @katjaq a lot easier! 
Re @katjaq's point on keeping the the `neuroview_contributors` and `contributors` as separate files, just to make sure that I understand what I am executing with the pipeline.
1. `neuroview_*` files will contain the sponsor and contributor of the neuroview paper, pulling information from OSF etc.; thus I am updating files in the pipeline to `neuroview_*` files
2. Old files created by me stay unchanged at the current stage
3. After this PR, `contributors` and `acknowledgements` will be reserved for Jupyter Book and any future contributions

I have completed the integration with a PR to @SNeuroble's branch :rocket: 
One important thing is I have migrated the original contents in `neuroview_*` to `data` and suffixed with `descriptions`.
If any text needs an update, please edit their counterparts under `data`!
Once that's merged, we can identify what still needs some work.

We willaddress where the scripts should live and source file for the auto-generated pages etc with issue #18

**Comment by SNeuroble** [comment]
Yes, this sounds perfect. There’s only one conflict (the TOC) so I’d say merge everything, keeping everyone’s files. Then update the TOC so that all the files are part of the selection menu.

Perhaps you can use our TOC to start bc it has separate parts for the evolving book and the neuroview (thx to Shawn for showing us how to use parts!). (We just didn’t have certain files like Hao-ting’s awesome contributions page bc they weren’t in the version we were working on, but we intended them to be there!)

**Comment by SNeuroble** [comment]
And just to clarify—instead of sending the PR back to our fork, could we just complete this merge of this PR into this repo? I think it might be quicker and we can do the fairly straightforward addition of files into TOC here.

**Comment by shawnrhoads** [comment]
Amazing, everyone! 🌟 

> And just to clarify—instead of sending the PR back to our fork, could we just complete this merge of this PR into this repo? I think it might be quicker and we can do the fairly straightforward addition of files into TOC here.

I think either a new PR to `main` after merging this branch, or a PR to `SNeuroble:update-neuroview_contents` before merging would work. If we merge @htwangtw's [PR](https://github.com/SNeuroble/brainhack_jupyter_book/pull/4) into `SNeuroble:update-neuroview_contents` then all updates would just appear on this PR anyway, right?

> Re @katjaq's point on keeping the the `neuroview_contributors` and `contributors` as separate files, just to make sure that I understand what I am executing with the pipeline, here are the steps (note to self):
> 
>     1. `neuroview_*` files will contain the sponsor and contributor of the neuroview paper, pulling information from OSF etc.; thus I am updating files in the pipeline to `neuroview_*` files
> 
>     2. Old files created by me stay unchanged at the current stage
> 
>     3. After this PR, `contributors` and `acknowledgements` will be reserved for Jupyter Book and any future contributions
> 
> 
> I have completed the integration with a PR to @SNeuroble's branch 🚀
> One important thing is I have migrated the original contents in `neuroview_*` to `data` and suffixed with `descriptions`.
> If any text needs an update, please edit their counterparts under `data`!
> Once that's merged, we can identify what still needs some work.
> 

Just briefly took a look at @htwangtw's awesome integration. Wow, so fast!! 🤩🤩 Would it be possible to write the tsv file from OSF to a file called `data/neuroview_contributors.tsv`? And copy the current `data/acknowledgments.csv` file to `data/neuroview_acknowledgments.csv`? Then, read those to the `neuroview_*` pages? 

We would also keep the current `data/contributors.tsv` and `data/acknowledgments.csv` as is (no deletion) and keep the lines in the Makefile to write these to non neuroview related pages (e.g., `acknowledgments.md` and `contributors.md`) as per @katjaq's great point earlier! The Makefile would then generate all 4 files (2 Neuroview and 2 non Neuroview). We can just add the non Neuroview files to the TOC at a later date.

This way, `data/neuroview_acknowledgments.csv` and `data/neuroview_contributors.tsv` would be static with regards to what is on OSF, but `data/contributors.tsv` and `data/acknowledgments.csv` can be continually updated as needed?

**Comment by htwangtw** [comment]
>And just to clarify—instead of sending the PR back to our fork, could we just complete this merge of this PR into this repo? I think it might be quicker and we can do the fairly straightforward addition of files into TOC here.
>>I think either a new PR to main after merging this branch, or a PR to SNeuroble:update-neuroview_contents before merging would work. If we merge @htwangtw's PR into SNeuroble:update-neuroview_contents then all updates would just appear on this PR anyway, right?

@shawnrhoads is correct here! Either way, we will achieve more or less the same results. I am very happy to open a separate PR for all I did so far to resolve the consistency in files.

>Just briefly took a look at @htwangtw's awesome integration. Wow, so fast!! star_struckstar_struck Would it be 
possible to write the tsv file from OSF to a file called data/neuroview_contributors.tsv? And copy the current data/acknowledgments.csv file to data/neuroview_acknowledgments.csv? Then, read those to the neuroview_* pages?

Sounds great! 
I know @Remi-Gau is still finalising the neuroview authors. 
For now, the content of `neuroview_*` and the files with no prepends are practically the same.
Once the authorship etc is all settled, I will remove the line pulling file from OSF and modify the `Makefile` accordingly. Also, my script really needs some serious cleanup afterwards haha

I have done all the changes mentioned by @shawnrhoads accordingly. I will let @SNeuroble to decide whether to merger my PR to her fork.

**Review by PeerHerholz — APPROVED** [review]
Holy guacamole, fantastic!

**Review by htwangtw — APPROVED** [review]
Happy to merge with or without my PR on @SNeuroble fork
Well done!

**Review by shawnrhoads — APPROVED** [review]

**Comment by PeerHerholz** [comment]
Someone needs to press the button, hehe.

**Comment by htwangtw** [comment]
Beep

**Comment by SNeuroble** [comment]
Woooo thanks all!

**Pull request merged**
