### PR TITLE
Multiple minor fixes for more consistentcy

### PR DESCRIPTION
**Pull request by yarikoptic**
individual commits might provide more info ;)

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@yarikoptic 
WAIT!!!! 

Before you send more!!!! >

The markdown here is not the source document. So any change you ask her has to be reported onto the google doc we are working on.

**Comment by Remi-Gau** [comment]
The best would be to report the changes on [psyarxiv](https://psyarxiv.com/rytjq) via hypothesis: helps us channel all the comment in one place

**How to**:
https://help.osf.io/hc/en-us/articles/360019738554-Annotate-a-Preprint

Sorry if that piece of info did not reach you.

**Comment by Remi-Gau** [comment]
To explain: the whole process was done in google docs because of the lower tech - bar.

**Comment by katjaq** [comment]
hello ! Thanks for spotting all these @yarikoptic ✨ 
I think that, if it is too much work to redo all the annotations on hypothesis, we can also accept the PR here and implement the exact same changes tomorrow during our final manuscript editing meeting? What do you think @Remi-Gau ? I can make sure we don't miss these changes. 
Happy with any solution though :)

Thanks again! 👋

**Comment by yarikoptic** [comment]
oi... I guess having `.github/PULL_REQUEST_TEMPLATE.md` with big `STOP!` might have helped ;)

**Comment by yarikoptic** [comment]
let me know what you decide, I can try redoing in another media

**Comment by SNeuroble** [comment]
Hi @yarikoptic , just a heads up that we incorporated your suggestions, so no need to redo them in hypothesis.
Thanks for your organized commits!

**Comment by yarikoptic** [comment]
Great, thank you! I guess we coughs just have this one closed then

**Pull request closed without merging**
