### PR TITLE
Update preprint figure

### PR DESCRIPTION
**Pull request by katjaq**
to the correct preprint version :D

### CODE REVIEW

**Review by htwangtw — APPROVED** [review]
LGTM!

**Comment by katjaq** [comment]
Thank you @htwangtw for the quick review :) 

I just wildly assigned some more people :D Please if you cannot find time , un-assign yourself <3 Just trying to move things quickly until preprint submission ;)

Thank you all :)

**Review by PeerHerholz — APPROVED** [review]
LGTM!

**Review by shawnrhoads — APPROVED** [review]
Awesome! Merge away!

**Pull request merged**
