### PR TITLE
ADD PR template and declutter

### LINKED ISSUE #56: Issue template for PR
Since we are dealing with a lot of spreadsheets, and their conversion to Markdown files, it might be useful to have a PR template that points out some of these things:
- update acknowledgement: `data/acknowledgment.csv`
- update existing author's social media link: `data/affiliation_and_consent_for_the_brainhack_neuroview_preprint_raw.tsv`

thoughts?

### PR DESCRIPTION
**Pull request by htwangtw**
Add a PR template to guild people to the relevant files for any update, especially for those files related to Github actions. Closed #56 

For files to update I addressed: 
- Manuscript
- Author affiliations
- Acknowledgment

File deleted for declutter:

- brainhack_book/acknowledgments.md
- brainhack_book/contributors.md
- data/affiliations_curated_ranked.tsv
- data/authors_affiliations.tsv
- data/contributors.tsv
- data/preprint_acknowledgments.csv
- data/preprint_contributors.tsv

I understand these can be confusing, so please let me know what's the more intuitive way to handle this.

### CODE REVIEW

**Review by anibalsolon — COMMENTED** [review]
Thank you @htwangtw ! The template looks good to me.

About the files:
Should these deleted files be in .gitignore?
And I'm sorry if I didn't quite catch that, but why the `tmp_` prefix in the scripts?

**Comment by htwangtw** [comment]
> About the files:
> Should these deleted files be in .gitignore?

My intention is to leave files that people should edit only in the repo. The .gitignore includes files that are generated with a full local build. I hope this makes sense. I will add interim files missing in the current .gitignore.

> And I'm sorry if I didn't quite catch that, but why the `tmp_` prefix in the scripts?

No need to apologies, this kind of confusion is why review exist! I was thinking that they are just intermediate steps so they can be cleaned off with the subsequent step (the bash script.) If they are useful we can keep them?

**Review by shawnrhoads — APPROVED** [review]
LGTM! Thanks for putting this together! :)

**Review by anibalsolon — APPROVED** [review]
Thank you for the explanation, it is clear to me now! It looks good to me :shipit:

**Comment by htwangtw** [comment]
Close this one as it's no longer relevant. Will isolate the PR template and submit a new PR.

**Pull request closed without merging**
