### PR TITLE
ENH/NF affiliation table clearner for author list in paper

### PR DESCRIPTION
**Pull request by htwangtw**
Original script by @SNeuroble, edited by @htwangtw.
As @katjaq suggested we add this curated author affiliation list to the jupyter book. Thanks to this suggestion, I have caught a few mistakes curated with my original curation! (Lession: always use git.)

The script extracts affiliation from OSF author spreadsheet, added unique ID to each author to allow manual curation on issues such as typos and same insitiute under different spelling etc.
The generated version and the curated version are stored in `data` for book keeping.
I also moved all the scripts to a new directory to keep track of them separately.
The `Makefile` now included the execution of this script.

### CODE REVIEW

**Comment by htwangtw** [comment]
I failed to add @SNeuroble as an author. Try again.

**Review by katjaq — APPROVED** [review]
Fantastic work @SNeuroble and @htwangtw ! Thanks 🚀 

Looks great to me, green light for merging this in! 💚 :)

**Comment by htwangtw** [comment]
Some extra update to add ranking.  This is a hack for the author list we have curated now.
The ranking spreadsheet was downloaded on 18:16 pm 02.11.2021
The download of the file is not automated due to API authorization needed.

The current steps are:
1. raw input processed by `neuroview_affiliations_organizer.sh`
2. Manual review the output from 1, generate `affiliations_curated.tsv`
3. run `neuroview_author_ranking.py` on __raw input__ and add ranking info to `affiliations_curated.tsv` (update from today)
The current workflow _adds ranking to the curated result_, ideally, I want to _add the human-curated data to the machine-generated ranking_, so mistakes from human are easier to spot.

I wrote the new script with the possibility of last-minute author list change and change to my ideal workflow in mind. In the case of adding new people to either ranking or raw sheet, and assuming new people will only be added to the bottom of the raw data (@Remi-Gau correct me if this is not the case), here's the workflow that leaves any human impact to the last stage
1. run `neuroview_author_ranking.py` on __raw input__ to add ranking info (need to remove a few lines at the bottom from the hacked version)
2. raw input processed by `neuroview_affiliations_organizer.sh`
3. update output from 2 with curated information and manually proofread new entries (match by author ID)

We are almost there :sparkles:

**Review by anibalsolon — APPROVED** [review]
Fantastic work indeed! Looks shiny for me ✨

**Comment by htwangtw** [comment]
Oops I just accidentally assigned extra people nvm

**Comment by htwangtw** [comment]
I just updated the script regarding my proposal yesterday. 
There's no change to the code any more. Only waiting for @Remi-Gau to say "THIS IS THE COMPLETE LIST", and then we are good.

Workflow:
1. fetch the raw file from OSF
2. check if there are new people not present in `affiliations_curated.tsv`, update this file
3. run python script, then the bash script
4. save the output to xlsx file and pass to AuthorArrange

Alternative workflow:
1. `make manuscript`, if the raw data has an update, it won't make the file. Update curated file to reflect the change.
2. run `make manuscript` again.

The benefit of this is we are not making changes to interim files so fewer mistakes are made by human.
If the code won't run, it's definitely the problem of 
1. curated file not update --> update curated file 
2. new edge case in authors not caught by script ---> check script

I will add a `README.md` to the `scripts` directory.

**Comment by htwangtw** [comment]
We have some question on mattermost related to this PR coming up. Can we have one more reviewer so this can be merged?

**Review by shawnrhoads — APPROVED** [review]
Great idea! :)

Also a fan of organizing scripts together in a separate directory.

All looks good to me! I'll merge now!

**Pull request merged**
