### PR TITLE
ENH: Test Jupyter notebooks

### PR DESCRIPTION
**Pull request by jhlegarreta**
Test Jupyter notebooks.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
I was tempted to add a separate workflow file, since the second test is not strictly necessary for the book to be deployed, but I discarded the idea because the workflow file would largely contain the same instructions as the current one, increasing the maintenance burden.

**Review by htwangtw — APPROVED** [review]
Thanks for this useful addition @jhlegarreta!

**Review by shawnrhoads — APPROVED** [review]
Cool! Thanks @jhlegarreta!

**Comment by htwangtw** [comment]
I am going to go ahead a merge this, and consider revising the three person rule - I think two is okay.

**Pull request merged**
