### PR TITLE
ADD requirements.txt files for contributors to built local test environment

### PR DESCRIPTION
**Pull request by htwangtw**
Add requirement files for python `virtualenv`

### CODE REVIEW

**Review by complexbrains — COMMENTED** [review]
I would only add [myst-nb](https://myst-nb.readthedocs.io/en/latest/) too I guess that might be required for parsing the markdown files in notebooks. Other than that seems alrighty to me but let's ask @PeerHerholz for his opinion.

**Comment by Remi-Gau** [comment]
Not sure if it is an overkill but since this script requires numpy, should we add it to both the requirements and the yml?

https://github.com/brainhackorg/brainhack_jupyter_book/blob/8cea5b99d07bbc8b8d2842222560dc8bc49e2a8f/scripts/neuroview_author_ranking.py#L29

**Comment by htwangtw** [comment]
Some of the things are possible handled by dependency checks - here's a fresh reinstall using this requirement file using `pip install -r requirements.txt`:

```
Successfully installed GitPython-3.1.13 Jinja2-2.11.3 MarkupSafe-1.1.1 PyYAML-5.4.1 Send2Trash-1.5.0 alabaster-0.7.12 argon2-cffi-20.1.0 async-generator-1.10 attrs-20.3.0 babel-2.9.0 backcall-0.2.0 beautifulsoup4-4.9.3 bleach-3.3.0 bokeh-2.2.3 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 chromedriver-binary-89.0.4389.23.0 click-7.1.2 click-plugins-1.1.1 cligj-0.7.1 colorama-0.4.4 decorator-4.4.2 defusedxml-0.6.0 docutils-0.16 entrypoints-0.3 fiona-1.8.18 geopandas-0.8.2 ghp-import-1.0.1 gitdb-4.0.5 idna-2.10 imagesize-1.2.0 importlib-metadata-3.6.0 ipykernel-5.5.0 ipython-7.20.0 ipython-genutils-0.2.0 ipywidgets-7.6.3 jedi-0.18.0 jsonschema-3.2.0 jupyter-book-0.10.0 jupyter-cache-0.4.2 jupyter-client-6.1.11 jupyter-core-4.7.1 jupyter-sphinx-0.3.1 jupyterlab-widgets-1.0.0 jupytext-1.8.2 latexcodec-2.0.1 linkify-it-py-1.0.1 markdown-it-py-0.6.2 mdit-py-plugins-0.2.5 mistune-0.8.4 modgrammar-0.10 munch-2.5.0 myst-nb-0.11.1 myst-parser-0.13.5 nbclient-0.5.2 nbconvert-5.6.1 nbdime-2.1.0 nbformat-5.1.2 nest-asyncio-1.5.1 nested-lookup-0.2.22 notebook-6.2.0 numpy-1.20.1 osf-1.12 packaging-20.9 pandas-1.2.2 pandocfilters-1.4.3 parso-0.8.1 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.1.0 prometheus-client-0.9.0 prompt-toolkit-3.0.16 ptyprocess-0.7.0 pybtex-0.24.0 pybtex-docutils-1.0.0 pycparser-2.20 pydata-sphinx-theme-0.4.3 pygments-2.8.0 pyparsing-2.4.7 pyproj-3.0.0.post1 pyrsistent-0.17.3 pyshp-2.1.3 python-dateutil-2.8.1 pytz-2021.1 pyzmq-22.0.3 requests-2.25.1 selenium-3.141.0 shapely-1.7.1 six-1.15.0 smmap-3.0.5 snowballstemmer-2.1.0 soupsieve-2.2 sphinx-3.5.1 sphinx-book-theme-0.0.39 sphinx-comments-0.0.3 sphinx-copybutton-0.3.1 sphinx-panels-0.5.2 sphinx-thebe-0.0.8 sphinx-togglebutton-0.2.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-bibtex-2.1.4 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 sqlalchemy-1.3.23 terminado-0.9.2 testpath-0.4.4 toml-0.10.2 tornado-6.1 traitlets-5.0.5 typing-extensions-3.7.4.3 uc-micro-py-1.0.1 urllib3-1.26.3 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.5.1 zipp-3.4.0
```

**Comment by Remi-Gau** [comment]
> Some of the things are possible handled by dependency checks - here's a fresh reinstall using this requirement file using `pip install -r requirements.txt`:
> 
> ```
> Successfully installed GitPython-3.1.13 Jinja2-2.11.3 MarkupSafe-1.1.1 PyYAML-5.4.1 Send2Trash-1.5.0 alabaster-0.7.12 argon2-cffi-20.1.0 async-generator-1.10 attrs-20.3.0 babel-2.9.0 backcall-0.2.0 beautifulsoup4-4.9.3 bleach-3.3.0 bokeh-2.2.3 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 chromedriver-binary-89.0.4389.23.0 click-7.1.2 click-plugins-1.1.1 cligj-0.7.1 colorama-0.4.4 decorator-4.4.2 defusedxml-0.6.0 docutils-0.16 entrypoints-0.3 fiona-1.8.18 geopandas-0.8.2 ghp-import-1.0.1 gitdb-4.0.5 idna-2.10 imagesize-1.2.0 importlib-metadata-3.6.0 ipykernel-5.5.0 ipython-7.20.0 ipython-genutils-0.2.0 ipywidgets-7.6.3 jedi-0.18.0 jsonschema-3.2.0 jupyter-book-0.10.0 jupyter-cache-0.4.2 jupyter-client-6.1.11 jupyter-core-4.7.1 jupyter-sphinx-0.3.1 jupyterlab-widgets-1.0.0 jupytext-1.8.2 latexcodec-2.0.1 linkify-it-py-1.0.1 markdown-it-py-0.6.2 mdit-py-plugins-0.2.5 mistune-0.8.4 modgrammar-0.10 munch-2.5.0 myst-nb-0.11.1 myst-parser-0.13.5 nbclient-0.5.2 nbconvert-5.6.1 nbdime-2.1.0 nbformat-5.1.2 nest-asyncio-1.5.1 nested-lookup-0.2.22 notebook-6.2.0 numpy-1.20.1 osf-1.12 packaging-20.9 pandas-1.2.2 pandocfilters-1.4.3 parso-0.8.1 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.1.0 prometheus-client-0.9.0 prompt-toolkit-3.0.16 ptyprocess-0.7.0 pybtex-0.24.0 pybtex-docutils-1.0.0 pycparser-2.20 pydata-sphinx-theme-0.4.3 pygments-2.8.0 pyparsing-2.4.7 pyproj-3.0.0.post1 pyrsistent-0.17.3 pyshp-2.1.3 python-dateutil-2.8.1 pytz-2021.1 pyzmq-22.0.3 requests-2.25.1 selenium-3.141.0 shapely-1.7.1 six-1.15.0 smmap-3.0.5 snowballstemmer-2.1.0 soupsieve-2.2 sphinx-3.5.1 sphinx-book-theme-0.0.39 sphinx-comments-0.0.3 sphinx-copybutton-0.3.1 sphinx-panels-0.5.2 sphinx-thebe-0.0.8 sphinx-togglebutton-0.2.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-bibtex-2.1.4 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 sqlalchemy-1.3.23 terminado-0.9.2 testpath-0.4.4 toml-0.10.2 tornado-6.1 traitlets-5.0.5 typing-extensions-3.7.4.3 uc-micro-py-1.0.1 urllib3-1.26.3 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.5.1 zipp-3.4.0
> ```

gotcha!! 

still need to learn more about this python thing. 

# :snake:

**Review by Remi-Gau — APPROVED** [review]
Good with me then!!

**Review by anibalsolon — COMMENTED** [review]
I would prefer to pin the lib versions, from the `freeze` output. WYT @htwangtw ?

**Comment by htwangtw** [comment]
That's a good idea so we are all working with the same environment. I can do that with the copy I work on.
The only thing I didn't test is @anibalsolon's test :laughing: because my chrome is old and I am lazy :see_no_evil: 
Can you check that perhaps?

**Comment by anibalsolon** [comment]
Yeah! I had the same problem- had to install the beta version 🙄 Lemme test that.

**Comment by htwangtw** [comment]
@anibalsolon and I discussed a bit and decided for the book it's probably enough to have a short form dependency list matching the conda yaml. We have less clutter and for a book, this should be sufficient :crossed_fingers:

**Review by anibalsolon — APPROVED** [review]
Neat and tidy!

**Comment by htwangtw** [comment]
Sorry I accidentally closed this..

**Comment by Remi-Gau** [comment]
> Sorry I accidentally closed this..

Happens to me VERY often

**Review by shawnrhoads — APPROVED** [review]

**Pull request merged**
