### PR TITLE
FIX Workflow

### PR DESCRIPTION
**Pull request by anibalsolon**
Thank you @htwangtw for noticing; the workflow was shamelessly broken since my change on the glossary references and passed unnoticed.

This PR fixes the problem of the reference extension and adds the compiling check into PRs. This means that PRs will not be merged until it passes the compilation test (including this PR!).

In order to make this PR pass, it was needed to fix the current problems of broken links and "file not in TOC" problems. Also, I've deleted my long-ass test in favor of the built-in checks, meaning fewer dependencies in the project 🎉 

I've tried to break every modification in commits, so to make it easier to understand, but please let me know if more details/reasoning is needed.

GO PLANET!

### CODE REVIEW

**Review by SamGuay — APPROVED** [review]
Appears all good to me + the check passed ;)

**Review by htwangtw — APPROVED** [review]
Tested everything locally - thanks so much for getting these fixed in such a short time and added so many great additions!

**Review by PeerHerholz — APPROVED** [review]
Great and important additions, thx a lot @anibalsolon!

**Comment by PeerHerholz** [comment]
Who's going to handle the `merge conflict`? *Peer walks away

**Comment by SamGuay** [comment]
Oh no, I broke something while trying to resolve conflicts. *Sam may run away*

**Comment by SamGuay** [comment]
@anibalsolon any cue by any chance? :innocent:

**Comment by htwangtw** [comment]
I will have a look

**Comment by htwangtw** [comment]
All green!

**Comment by anibalsolon** [comment]
HAHA thank you @PeerHerholz @SamGuay @htwangtw !!!

**Comment by htwangtw** [comment]
WELL look like we might have some cached file issue... I will check on my fork and see if I can diagnose that a bit

**Pull request merged**
