### PR TITLE
Curate author affiliations for submitting the final proof

### PR DESCRIPTION
**Pull request by htwangtw**
Changes in this pull request:
- Scripts are updated to read curated spreadsheet. No need to change user behaviour
- Can people help with the final curation?

We are now asking co authors to check their details on this [google sheet](https://docs.google.com/spreadsheets/d/1FPXZeG09c0BT4aCfynAgkjFozl16oM3GkDVeRgpj4d0/edit#gid=0). It is a mirror of `affiliation_curated.tsv`

If we want to cross check internally, compare that google sheet above with: 

- [this one for the first 157 people](https://github.com/brainhackorg/brainhack_jupyter_book/blob/main/data/contributors/neuroview/affiliation_and_consent_for_the_brainhack_neuroview_preprint_raw.tsv)
- the rest to [this file](https://github.com/brainhackorg/brainhack_jupyter_book/blob/main/data/contributors/neuroview/affiliation_consent_and_contributions_for_the_brainhack_consortium_tripetto_raw.csv)

Work needed: 
- [x] update `data/contributors/neuroview/affiliation_curated.tsv`
- [x] re-run script with the following command `bash scripts/neuroview_affiliations_organizer.sh update`
- [x] update `data/contributors/neuroview_contributors.tsv`

cc' @Remi-Gau

### CODE REVIEW

**Comment by htwangtw** [comment]
This PR handles the affiliations and the one case of incomplete surname in #69 
Looks fine on my side now but would appriciate more checkes.

**Comment by SNeuroble** [comment]
Diff'ed data/contributors/neuroview/affiliation_curated.tsv against affiliation_curated.tsv google sheet.
Found 2 differences:
5  1   Davide      Momi    Department of Neuroscience, Imaging and Clinical Sciences   "University ""G. d'Annunzio"" of Chieti"    Chieti  Italy 
192    1   Lisa        Novello Center for Mind Brain Sciences (CIMeC)  University of Trento    Trento  Italy   Italy

I think for Davide, the quotation marks should be removed.
For Lisa, there is an extra "Italy".

(I'm continuing to review the other files!)

**Comment by SNeuroble** [comment]
For the record: as per @htwangtw 's request, we are holding off on accepting this PR until after community review of affiliations. Should hopefully finish within the coming days.

**Comment by Remi-Gau** [comment]
> Diff'ed data/contributors/neuroview/affiliation_curated.tsv against affiliation_curated.tsv google sheet.
> Found 2 differences:
> 5 1 Davide Momi Department of Neuroscience, Imaging and Clinical Sciences "University ""G. d'Annunzio"" of Chieti" Chieti Italy
> 192 1 Lisa Novello Center for Mind Brain Sciences (CIMeC) University of Trento Trento Italy Italy
> 
> I think for Davide, the quotation marks should be removed.
> For Lisa, there is an extra "Italy".
> 
> (I'm continuing to review the other files!)

Thanks for doing this @SNeuroble 

I think that it'd be good to keep a final "git diff" of the changes made: to implement them "manually" in the proofs.

**Comment by htwangtw** [comment]
As the paper is done, and no more changes were made. I will go ahead and merge this one.

**Pull request merged**
