### PR TITLE
Added acknowledgements.csv file to data/

### PR DESCRIPTION
**Pull request by shawnrhoads**
Converted the list of acknowledgements in [preprint](https://docs.google.com/document/d/1Fxvnqcod08CvGat8MxxvptuxBIFRZrnXBUUaMm_cBew/edit#) to a comma-separated table for the Acknowledgements page (#9).

These data will be referenced once the Acknowledgements page is added to the Jupyter Book.

### CODE REVIEW

**Review by PeerHerholz — APPROVED** [review]
LGTM!

**Review by htwangtw — APPROVED** [review]
Looks good to me!

**Review by Remi-Gau — APPROVED** [review]
Thanks for that

**Review by katjaq — APPROVED** [review]
Fantastic! Thanks so much @shawnrhoads 🚀

**Comment by shawnrhoads** [comment]
Awesome, thanks everyone! I'll go ahead and merge it! 😄

**Pull request merged**
